server.port=8081
spring.application.name=auth-service
springdoc.api-docs.path=/api/v1/auth/v3/api-docs

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/edulearn_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=18138920
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
# Secret key should be at least 256 bits (32 chars)
app.jwt.secret=edulearn_lms_super_secret_key_change_in_production_1234567890
app.jwt.expiration-ms=86400000

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
eureka.instance.hostname=localhost
